#!/bin/bash

echo "🚀 LANCEMENT VERSION COMPLÈTE - Portail Entreprise Flashback Fa v2.0"
echo "====================================================================="

echo ""
echo "📋 Vérification de l'état actuel des services..."
sudo supervisorctl status

echo ""
echo "🔄 Redémarrage de tous les services pour la version complète..."
sudo supervisorctl restart all

echo ""
echo "⏳ Attente du démarrage des services (15 secondes)..."
sleep 15

echo ""
echo "✅ Vérification de l'état final..."
sudo supervisorctl status

echo ""
echo "🌐 Test de connectivité..."
frontend_status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
backend_status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8001/api/)

echo "Frontend: $frontend_status"
echo "Backend: $backend_status"

if [ "$frontend_status" = "200" ] && [ "$backend_status" = "200" ]; then
    echo ""
    echo "🎉 VERSION COMPLÈTE LANCÉE AVEC SUCCÈS !"
    echo "====================================================================="
    echo ""
    echo "📍 ACCÈS À L'APPLICATION:"
    echo "   🔗 URL: http://localhost:3000"
    echo ""
    echo "🆕 TOUTES LES FONCTIONNALITÉS DISPONIBLES:"
    echo ""
    echo "   ✅ PROBLÈMES RÉSOLUS:"
    echo "   • Tous les boutons réparés et fonctionnels"
    echo "   • Navigation fluide dans toute l'application"
    echo "   • Exports Excel opérationnels"
    echo ""
    echo "   🚀 NOUVELLES FONCTIONNALITÉS:"
    echo "   • Page 'Gestion des Entreprises' complète"
    echo "   • Formulaire d'ajout d'entreprise avec 4 champs:"
    echo "     - Nom de l'entreprise"
    echo "     - ID Guild Discord"
    echo "     - ID Rôle Principal"
    echo "     - 🆕 ID Rôle Membre (pour compter employés)"
    echo "   • Configuration rôles Dot Guild (Staff/Patron/Co-Patron/DOT)"
    echo "   • Bouton 'Page Principale' pour navigation"
    echo "   • Interface responsive et cohérente"
    echo ""
    echo "   🎭 MODE DÉVELOPPEMENT:"
    echo "   • Connexion automatique (rôle Staff)"
    echo "   • Accès complet à toutes les fonctionnalités"
    echo "   • Tests et développement facilités"
    echo ""
    echo "🎯 GUIDE D'UTILISATION RAPIDE:"
    echo "   1. 🌐 Ouvrir http://localhost:3000"
    echo "   2. 🎭 Connexion automatique en tant que Staff"
    echo "   3. 👆 Cliquer sur 'Gestion Entreprises' (header, bouton violet)"
    echo "   4. ➕ Tester l'ajout d'une nouvelle entreprise"
    echo "   5. ⚙️  Configurer les rôles dans l'onglet 'Configuration Rôles'"
    echo "   6. 🏠 Utiliser 'Page Principale' pour retourner au dashboard"
    echo ""
    echo "🔧 FONCTIONNALITÉS AVANCÉES:"
    echo "   • Export Excel sur toutes les pages (Impôts, Blanchiment, etc.)"
    echo "   • Zone copier-coller pour import de données"
    echo "   • Système de rôles et permissions"
    echo "   • Configuration entreprise complète"
    echo ""
    echo "📊 COMPTAGE D'EMPLOYÉS:"
    echo "   • Le champ 'ID Rôle Membre' permet de compter automatiquement"
    echo "   • le nombre d'employés ayant ce rôle dans Discord"
    echo "   • Statistiques en temps réel des effectifs par entreprise"
    echo ""
    echo "🛠️  SCRIPTS DISPONIBLES:"
    echo "   • bash /app/launch-version-complete.sh (ce script)"
    echo "   • bash /app/switch-to-production.sh (Discord réel)"
    echo "   • bash /app/restore-mock-mode.sh (retour développement)"
    echo ""
    echo "📋 LOGS EN TEMPS RÉEL:"
    echo "   Frontend: tail -f /var/log/supervisor/frontend.out.log"
    echo "   Backend:  tail -f /var/log/supervisor/backend.out.log"
    echo ""
    echo "====================================================================="
    echo "🎊 VOTRE APPLICATION EST PRÊTE AVEC TOUTES LES AMÉLIORATIONS !"
    echo "====================================================================="
else
    echo ""
    echo "⚠️  PROBLÈME DÉTECTÉ:"
    echo "   Frontend Status: $frontend_status (attendu: 200)"
    echo "   Backend Status: $backend_status (attendu: 200)"
    echo ""
    echo "🔍 VÉRIFICATION DES LOGS:"
    echo "   sudo tail -n 20 /var/log/supervisor/frontend.err.log"
    echo "   sudo tail -n 20 /var/log/supervisor/backend.err.log"
    echo ""
    echo "🔄 TENTATIVE DE REDÉMARRAGE:"
    echo "   sudo supervisorctl restart all"
fi