"""Initial migration with all tables

Revision ID: 50c6762cd7cb
Revises: 
Create Date: 2025-09-05 18:06:46.967289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c6762cd7cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guild_id', sa.String(length=20), nullable=False),
    sa.Column('guild_name', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('enterprises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('discord_guild_id', sa.String(length=20), nullable=False),
    sa.Column('main_guild_role_id', sa.String(length=20), nullable=True),
    sa.Column('staff_role_id', sa.String(length=20), nullable=True),
    sa.Column('patron_role_id', sa.String(length=20), nullable=True),
    sa.Column('co_patron_role_id', sa.String(length=20), nullable=True),
    sa.Column('dot_role_id', sa.String(length=20), nullable=True),
    sa.Column('member_role_id', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_guild_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('grade_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grade_name', sa.String(length=50), nullable=False),
    sa.Column('salaire_base', sa.Float(), nullable=True),
    sa.Column('prime_base', sa.Float(), nullable=True),
    sa.Column('ca_multiplier', sa.Float(), nullable=True),
    sa.Column('prime_multiplier', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_name')
    )
    op.create_table('tax_brackets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bracket_type', sa.String(length=20), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blanchiment_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('use_global_settings', sa.Boolean(), nullable=True),
    sa.Column('perc_entreprise', sa.Float(), nullable=True),
    sa.Column('perc_groupe', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discord_id', sa.String(length=20), nullable=False),
    sa.Column('discord_username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('STAFF', 'PATRON', 'CO_PATRON', 'DOT', 'EMPLOYE', name='userrole'), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_table('archives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archive_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('EN_ATTENTE', 'VALIDE', 'REFUSE', name='archivestatus'), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('archive_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blanchiment_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('EN_COURS', 'TERMINE', 'SUSPENDU', 'ANNULE', name='blanchimentstatus'), nullable=True),
    sa.Column('date_recu', sa.Date(), nullable=True),
    sa.Column('date_rendu', sa.Date(), nullable=True),
    sa.Column('duree_jours', sa.Integer(), nullable=True),
    sa.Column('groupe', sa.String(length=50), nullable=False),
    sa.Column('employe', sa.String(length=100), nullable=False),
    sa.Column('donneur_id', sa.String(length=50), nullable=True),
    sa.Column('recepteur_id', sa.String(length=50), nullable=True),
    sa.Column('somme', sa.Float(), nullable=False),
    sa.Column('entreprise_perc', sa.Float(), nullable=False),
    sa.Column('groupe_perc', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.Enum('FACTURE', 'DIPLOME', 'CONTRAT', 'RAPPORT', 'DOCUMENT', name='documenttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dotation_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('EN_ATTENTE', 'VALIDE', 'REFUSE', name='archivestatus'), nullable=True),
    sa.Column('total_ca', sa.Float(), nullable=True),
    sa.Column('total_salaires', sa.Float(), nullable=True),
    sa.Column('total_primes', sa.Float(), nullable=True),
    sa.Column('total_employees', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_declarations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('revenus_totaux', sa.Float(), nullable=True),
    sa.Column('revenus_imposables', sa.Float(), nullable=True),
    sa.Column('abattements', sa.Float(), nullable=True),
    sa.Column('patrimoine', sa.Float(), nullable=True),
    sa.Column('impot_revenus', sa.Float(), nullable=True),
    sa.Column('impot_patrimoine', sa.Float(), nullable=True),
    sa.Column('impot_total', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('EN_ATTENTE', 'VALIDE', 'REFUSE', name='archivestatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dotation_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('run', sa.Float(), nullable=True),
    sa.Column('facture', sa.Float(), nullable=True),
    sa.Column('vente', sa.Float(), nullable=True),
    sa.Column('ca_total', sa.Float(), nullable=True),
    sa.Column('salaire', sa.Float(), nullable=True),
    sa.Column('prime', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['dotation_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dotation_rows')
    op.drop_table('tax_declarations')
    op.drop_table('dotation_reports')
    op.drop_table('documents')
    op.drop_table('blanchiment_operations')
    op.drop_table('audit_logs')
    op.drop_table('archives')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('blanchiment_settings')
    op.drop_table('tax_brackets')
    op.drop_table('grade_rules')
    op.drop_table('enterprises')
    op.drop_table('discord_configs')
    # ### end Alembic commands ###
